### ISSUE TITLE
Requires C++17 but is not stated anywhere.

### ISSUE THREAD

**Issue by timbeaudet** [mariusbancila/stduuid#15]
"A C++ cross-platform single-header library implementation" should become "A C++17 cross-platform multi-header library implementation" as it requires C++17 and has multiple headers.

**Comment by mariusbancila** [comment]
That is correct, it is a C++17 library. I can change that to make it more clear.

However, there is the following paragraph in the description:

**As the proposal evolves based on the standard committee and the C++ community feedback, this library implementation will reflect those changes.** 

This library is an implementation of the standard proposal that you can find [here](https://github.com/mariusbancila/stduuid/blob/master/P0959.md). So in the future the library might require C++20. For instance, it uses std::span, which is a C++20 feature. The current implementation uses gls::span, and that's why you may see more headers. But apart from that, the library is a single-header.

**Comment by timbeaudet** [comment]
Sure, more clarity would be nice as I'm using C++11 in a project and spent a bit of time starting to integrate... until I realized what was required. 👍

**Comment by mariusbancila** [comment]
This is stated now in the description.
