### ISSUE TITLE
uuid.h and uuid/uuid.h

### ISSUE THREAD

**Issue by clauderobi** [mariusbancila/stduuid#17]
I guess if uuid.h loads uuid/uuid.h this means that stduuid has a dependency on the system uuid.h This is not stated anywhere; I was under the impression that stduuid would be complete by itself.

 Also, IMHO using the same filename is problematic. Do you intend to stick to this?

**Comment by mariusbancila** [comment]
It is stated in the readme that the `uuid_system_generator` is **a function object that generates new UUIDs using operating system resources (CoCreateGuid on Windows, uuid_generate on Linux, CFUUIDCreate on Mac)**. This implies dependencies on system APIs.

However, since this can be a problem for some scenarios I have changed it so that `uuid_system_generator` is only defined if the `UUID_SYSTEM_GENERATOR` macro is available. 

If you need `uuid_system_generator` you must add this `UUID_SYSTEM_GENERATOR` to your preprocessor definitions, or directly supply `-DUUID_SYSTEM_GENERATOR` to the compiler. Otherwise, this will not be available and those headers will not be inclulded.
